CREATE TABLE AJAX_COMMENT (
    ID        NUMBER(4)   PRIMARY KEY,
    NAME      VARCHAR2(20) NOT NULL,
    CONTENT   VARCHAR2(1000) NOT NULL
);

CREATE TABLE ID_REPOSITORY (
    NAME      VARCHAR2(20)  PRIMARY KEY,
    VALUE     NUMBER(4)
);

INSERT INTO ID_REPOSITORY VALUES('COMMENT', 0);